# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20161105_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=11)),
                ('receive_mode', models.IntegerField(default=2, max_length=11)),
                ('storages', models.CharField(max_length=11)),
                ('receive_name', models.CharField(blank=True, max_length=200, null=True)),
                ('receive_mob', models.CharField(blank=True, max_length=20, null=True)),
                ('receive_address', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(max_length=11)),
                ('freight', models.IntegerField(max_length=11)),
                ('total_fee', models.IntegerField(max_length=11)),
                ('seq', models.IntegerField(default=0, max_length=11)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('obtain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('obtain_mob', models.CharField(blank=True, max_length=20, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('bulk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Bulk')),
            ],
        ),
    ]
