# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='logistics',
            field=models.IntegerField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='mob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.IntegerField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(default=1991, max_length=11),
            preserve_default=False,
        ),
    ]
