# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20161114_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_time',
            field=models.DateTimeField(),
        ),
    ]
